// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLoocNs7wCDpkO4sRECdggKBsmFHIA2E8',
    appId: '1:932561304898:web:087ce7cf8c23ec616bdcdb',
    messagingSenderId: '932561304898',
    projectId: 'kapoktest-76750',
    authDomain: 'kapoktest-76750.firebaseapp.com',
    storageBucket: 'kapoktest-76750.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9p0CqwttGzgYWwL8SE1M6rGeg4_9ki_M',
    appId: '1:932561304898:android:4bfd548cffbeadd66bdcdb',
    messagingSenderId: '932561304898',
    projectId: 'kapoktest-76750',
    storageBucket: 'kapoktest-76750.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1PRiXmRWvMWB9UN8BFQs-vzCJx1GODPQ',
    appId: '1:932561304898:ios:289501ce924093506bdcdb',
    messagingSenderId: '932561304898',
    projectId: 'kapoktest-76750',
    storageBucket: 'kapoktest-76750.appspot.com',
    iosBundleId: 'com.flutterflow.kapok2',
  );
}
